modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="coppercarts"
version="${file.jarVersion}"
displayName="Faster Minecarts on Copper Blocks"
authors="DahakaMVl"
description='''
Minecarts are faster when moving over rails that are placed on copper blocks.
'''